name: Feature Request
description: Suggest new functionality or an improvement
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What are you trying to do? What's missing or painful today?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work? Include config examples, CLI flags, or behavior descriptions if relevant.
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area does this relate to?
      options:
        - detection rules / behavioral patterns
        - scanners
        - sentinel / file integrity
        - network monitoring
        - clawsudo policies
        - TUI dashboard
        - Slack / alerting
        - API
        - config system
        - agent integration
        - installer / deployment
        - documentation
        - other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
    validations:
      required: false
